// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWNndM_PgPZQ6zAXNvRurYu7PeoM21We8',
    appId: '1:734320394849:web:9a25c3cbad827c5204e020',
    messagingSenderId: '734320394849',
    projectId: 'docnet-alpha',
    authDomain: 'docnet-alpha.firebaseapp.com',
    storageBucket: 'docnet-alpha.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMAfGKkmup1jtrVF5dJb5JSQYazqCU-oc',
    appId: '1:734320394849:android:c779ce9abf5f7d5b04e020',
    messagingSenderId: '734320394849',
    projectId: 'docnet-alpha',
    storageBucket: 'docnet-alpha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbgFJd3r04fgIOxVDUerpea2emsHS7zX0',
    appId: '1:734320394849:ios:cb4d493f37a123a204e020',
    messagingSenderId: '734320394849',
    projectId: 'docnet-alpha',
    storageBucket: 'docnet-alpha.appspot.com',
    iosClientId: '734320394849-ourjke75gkjls312nv9e3o6lsicb8qlf.apps.googleusercontent.com',
    iosBundleId: 'com.example.docnet',
  );
}
